## ML


In [3]:
print("hello world")

hello world


In [4]:
import numpy as np

In [5]:
zeros_array = np.full(10,3)
zeros_array

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [6]:
mylist = [2, 3, 4]
array_from_list = np.array(mylist)
array_from_list

array([2, 3, 4])

In [7]:
linspace_array = np.linspace(0, 1, 11)  # Creates 11 numbers from 0 to 1
linspace_array

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [8]:
zeros_matrix = np.zeros((5, 2))
ones_matrix = np.ones((5, 2))
constant_matrix = np.full((5, 2 ,2), 3)
#zeros_matrix
#ones_matrix
constant_matrix

array([[[3, 3],
        [3, 3]],

       [[3, 3],
        [3, 3]],

       [[3, 3],
        [3, 3]],

       [[3, 3],
        [3, 3]],

       [[3, 3],
        [3, 3]]])

In [9]:
arr = np.array([[2, 3, 4], [4, 5, 6], [7, 5, 2]])
first_row = arr[1]      # Gets the first row
first_col = arr[1, :]  # Gets the first column

In [10]:
first_col

array([4, 5, 6])

In [11]:
np.random.seed(4)  # Set the seed
random_array = np.random.rand(5, 4)  # Generates random numbers between 0 and 1

In [12]:
random_array

array([[0.96702984, 0.54723225, 0.97268436, 0.71481599],
       [0.69772882, 0.2160895 , 0.97627445, 0.00623026],
       [0.25298236, 0.43479153, 0.77938292, 0.19768507],
       [0.86299324, 0.98340068, 0.16384224, 0.59733394],
       [0.0089861 , 0.38657128, 0.04416006, 0.95665297]])

In [13]:
normal_distribution = np.random.randn(5, 2)
random_integers = np.random.randint(low=0, high=100, size=(5, 4))

In [14]:
random_integers

array([[17, 81, 89, 73],
       [59, 48, 76, 23],
       [94, 22, 67, 62],
       [62, 75, 23, 56],
       [70, 71, 73, 82]])

In [15]:
arr

array([[2, 3, 4],
       [4, 5, 6],
       [7, 5, 2]])

In [16]:
arr = arr + 1 

In [17]:
arr

array([[3, 4, 5],
       [5, 6, 7],
       [8, 6, 3]])

In [18]:
arr / 2

array([[1.5, 2. , 2.5],
       [2.5, 3. , 3.5],
       [4. , 3. , 1.5]])

In [19]:
np.ones(4)

array([1., 1., 1., 1.])

In [20]:
np.full(4, 3)


array([3, 3, 3, 3])

In [21]:
arr1 / arr2

NameError: name 'arr1' is not defined

In [22]:
arr = np.array([1, 2, 3, 4])

In [23]:
arr > 2

array([False, False,  True,  True])

In [24]:
arr[arr < 1]

array([], dtype=int64)

In [25]:
arr.()

SyntaxError: invalid syntax (988131475.py, line 1)

In [26]:
u = np.array([2,4,6,7])
v = np.array([3,6,7,8])

In [27]:
2 * u

array([ 4,  8, 12, 14])

In [28]:
u

array([2, 4, 6, 7])

In [29]:
v

array([3, 6, 7, 8])

In [30]:
u + v

array([ 5, 10, 13, 15])

In [31]:
u - v

array([-1, -2, -1, -1])

In [32]:
u.shape[0]

4

In [33]:
def vector_vector_multiplication (u, v):
    assert u.shape[0] == v.shape

In [34]:
np.eye(12)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [35]:
import numpy as np
import pandas as pd

In [36]:
data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]

columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicle_Style', 'MSRP'
]

In [37]:
df = pd.DataFrame(data, columns=columns)
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [59]:
df.head(5)

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [39]:
df[['Model', 'Year']]

Model  Year
0    Stanza  1991
1    Sonata  2017
2     Elise  2010
3    Acadia  2017
4  Frontier  2017

In [61]:
col_name = 'Engine HP'
df[col_name]

0    138.0
1      NaN
2    218.0
3    194.0
4    261.0
Name: Engine HP, dtype: float64

In [62]:
df['id'] = ['jide', 'Nike', 'bisi', 'bode', 'tito'] 
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP    id  
0         sedan   2000  jide  
1         Sedan  27150  Nike  
2   convertible  54990  bisi  
3       4dr SUV  34450  bode  
4        Pickup  32340  tito

In [63]:
del df['id']
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [43]:
df.columns

Index(['Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
       'Transmission Type', 'Vehicle_Style', 'MSRP'],
      dtype='object')

In [44]:
idx = np.arange(5)
idx

array([0, 1, 2, 3, 4])

In [45]:
np.random.seed(2)
np.random.shuffle(idx)
idx

array([2, 4, 1, 3, 0])

In [46]:
df.iloc[idx]

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
2    Lotus     Elise  2010      218.0                 4            MANUAL   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
0   Nissan    Stanza  1991      138.0                 4            MANUAL   

  Vehicle_Style   MSRP  
2   convertible  54990  
4        Pickup  32340  
1         Sedan  27150  
3       4dr SUV  34450  
0         sedan   2000

In [47]:
df.loc[[0,1]]

Make   Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan  Stanza  1991      138.0                 4            MANUAL   
1  Hyundai  Sonata  2017        NaN                 4         AUTOMATIC   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150

In [48]:
df.index= ['a', 'b', 'c', 'd', 'e']
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
a   Nissan    Stanza  1991      138.0                 4            MANUAL   
b  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
c    Lotus     Elise  2010      218.0                 4            MANUAL   
d      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
e   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
a         sedan   2000  
b         Sedan  27150  
c   convertible  54990  
d       4dr SUV  34450  
e        Pickup  32340

In [49]:

df.reset_index(drop=True)

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [50]:
n_train = 3
n_val = 1
n_test = 1

In [51]:
df_train = df.iloc[:n_train]
df_train

Make   Model  Year  Engine HP  Engine Cylinders Transmission Type  \
a   Nissan  Stanza  1991      138.0                 4            MANUAL   
b  Hyundai  Sonata  2017        NaN                 4         AUTOMATIC   
c    Lotus   Elise  2010      218.0                 4            MANUAL   

  Vehicle_Style   MSRP  
a         sedan   2000  
b         Sedan  27150  
c   convertible  54990

In [52]:
df_val = df.iloc[n_train:n_train+n_val]
df_val

Make   Model  Year  Engine HP  Engine Cylinders Transmission Type  \
d  GMC  Acadia  2017      194.0                 4         AUTOMATIC   

  Vehicle_Style   MSRP  
d       4dr SUV  34450

In [53]:
df_test = df.iloc[n_train+n_val:]
df_test

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
e  Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
e        Pickup  32340

In [54]:
df = df.reset_index(drop=True)
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [55]:

df['Make'] == 'Nissan'

0     True
1    False
2    False
3    False
4     True
Name: Make, dtype: bool

In [56]:
df[df['Make'] == 'Nissan']

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0  Nissan    Stanza  1991      138.0                 4            MANUAL   
4  Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
4        Pickup  32340

In [57]:
df.columns

Index(['Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
       'Transmission Type', 'Vehicle_Style', 'MSRP'],
      dtype='object')

In [64]:
df.columns

Index(['Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
       'Transmission Type', 'Vehicle_Style', 'MSRP'],
      dtype='object')

In [ ]:
df.columns.str.lower().str.replace(' ','_')

Index(['make', 'model', 'year', 'engine hp', 'engine cylinders',
       'transmission type', 'vehicle_style', 'msrp'],
      dtype='object')

In [109]:
df.columns = df.columns.str.lower().str.replace(' ','_')

In [110]:
df

make     model  year  engine_hp  engine_cylinders transmission_type  \
0   nissan    stanza  1991      138.0                 4            manual   
1  hyundai    sonata  2017        NaN                 4         automatic   
2    lotus     elise  2010      218.0                 4            manual   
3      gmc    acadia  2017      194.0                 4         automatic   
4   nissan  frontier  2017      261.0                 6            manual   

  vehicle_style   msrp  
0         sedan   2000  
1         sedan  27150  
2   convertible  54990  
3       4dr_suv  34450  
4        pickup  32340

In [ ]:
df.dtypes

Make                  object
Model                 object
Year                   int64
Engine HP            float64
Engine Cylinders       int64
Transmission Type     object
Vehicle_Style         object
MSRP                   int64
dtype: object

In [71]:
df.dtypes.index

Index(['Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
       'Transmission Type', 'Vehicle_Style', 'MSRP'],
      dtype='object')

In [91]:
df.dtypes[df.dtypes=='object'].index

Index(['Make', 'Model', 'Transmission Type', 'Vehicle_Style'], dtype='object')

In [92]:
list(df.dtypes[df.dtypes=='object'].index)

['Make', 'Model', 'Transmission Type', 'Vehicle_Style']

In [93]:
string_columns = df.dtypes[df.dtypes == 'object'].index

for col in string_columns:
    df[col] = df[col].str.lower().str.replace(' ', '_')

df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   nissan    stanza  1991      138.0                 4            manual   
1  hyundai    sonata  2017        NaN                 4         automatic   
2    lotus     elise  2010      218.0                 4            manual   
3      gmc    acadia  2017      194.0                 4         automatic   
4   nissan  frontier  2017      261.0                 6            manual   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         sedan  27150  
2   convertible  54990  
3       4dr_suv  34450  
4        pickup  32340

In [90]:
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   nissan    stanza  1991      138.0                 4            manual   
1  hyundai    sonata  2017        NaN                 4         automatic   
2    lotus     elise  2010      218.0                 4            manual   
3      gmc    acadia  2017      194.0                 4         automatic   
4   nissan  frontier  2017      261.0                 6            manual   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         sedan  27150  
2   convertible  54990  
3       4dr_suv  34450  
4        pickup  32340

In [94]:
df.MSRP

0     2000
1    27150
2    54990
3    34450
4    32340
Name: MSRP, dtype: int64

In [96]:
df.MSRP.min(), df.MSRP.max(), df.MSRP.mean(), df.MSRP.std()

(np.int64(2000),
 np.int64(54990),
 np.float64(30186.0),
 np.float64(18985.044903818372))

In [97]:
df.MSRP.describe()

count        5.000000
mean     30186.000000
std      18985.044904
min       2000.000000
25%      27150.000000
50%      32340.000000
75%      34450.000000
max      54990.000000
Name: MSRP, dtype: float64

In [100]:
df.describe().round(2)

Year  Engine HP  Engine Cylinders      MSRP
count     5.00       4.00              5.00      5.00
mean   2010.40     202.75              4.40  30186.00
std      11.26      51.30              0.89  18985.04
min    1991.00     138.00              4.00   2000.00
25%    2010.00     180.00              4.00  27150.00
50%    2017.00     206.00              4.00  32340.00
75%    2017.00     228.75              4.00  34450.00
max    2017.00     261.00              6.00  54990.00

In [101]:
df.nunique()

Make                 4
Model                5
Year                 3
Engine HP            4
Engine Cylinders     2
Transmission Type    2
Vehicle_Style        4
MSRP                 5
dtype: int64

In [106]:
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   nissan    stanza  1991      138.0                 4            manual   
1  hyundai    sonata  2017        NaN                 4         automatic   
2    lotus     elise  2010      218.0                 4            manual   
3      gmc    acadia  2017      194.0                 4         automatic   
4   nissan  frontier  2017      261.0                 6            manual   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         sedan  27150  
2   convertible  54990  
3       4dr_suv  34450  
4        pickup  32340

In [111]:
df.isnull()

make  model   year  engine_hp  engine_cylinders  transmission_type  \
0  False  False  False      False             False              False   
1  False  False  False       True             False              False   
2  False  False  False      False             False              False   
3  False  False  False      False             False              False   
4  False  False  False      False             False              False   

   vehicle_style   msrp  
0          False  False  
1          False  False  
2          False  False  
3          False  False  
4          False  False

In [112]:
df.isnull().sum()

make                 0
model                0
year                 0
engine_hp            1
engine_cylinders     0
transmission_type    0
vehicle_style        0
msrp                 0
dtype: int64

In [114]:
df.engine_hp.fillna(0)

0    138.0
1      0.0
2    218.0
3    194.0
4    261.0
Name: engine_hp, dtype: float64

In [115]:
df.engine_hp.fillna(df.engine_hp.mean())

0    138.00
1    202.75
2    218.00
3    194.00
4    261.00
Name: engine_hp, dtype: float64

In [116]:
df

make     model  year  engine_hp  engine_cylinders transmission_type  \
0   nissan    stanza  1991      138.0                 4            manual   
1  hyundai    sonata  2017        NaN                 4         automatic   
2    lotus     elise  2010      218.0                 4            manual   
3      gmc    acadia  2017      194.0                 4         automatic   
4   nissan  frontier  2017      261.0                 6            manual   

  vehicle_style   msrp  
0         sedan   2000  
1         sedan  27150  
2   convertible  54990  
3       4dr_suv  34450  
4        pickup  32340

In [117]:
df.engine_hp = df.engine_hp.fillna(df.engine_hp.mean())
df

make     model  year  engine_hp  engine_cylinders transmission_type  \
0   nissan    stanza  1991     138.00                 4            manual   
1  hyundai    sonata  2017     202.75                 4         automatic   
2    lotus     elise  2010     218.00                 4            manual   
3      gmc    acadia  2017     194.00                 4         automatic   
4   nissan  frontier  2017     261.00                 6            manual   

  vehicle_style   msrp  
0         sedan   2000  
1         sedan  27150  
2   convertible  54990  
3       4dr_suv  34450  
4        pickup  32340

In [118]:
df

make     model  year  engine_hp  engine_cylinders transmission_type  \
0   nissan    stanza  1991     138.00                 4            manual   
1  hyundai    sonata  2017     202.75                 4         automatic   
2    lotus     elise  2010     218.00                 4            manual   
3      gmc    acadia  2017     194.00                 4         automatic   
4   nissan  frontier  2017     261.00                 6            manual   

  vehicle_style   msrp  
0         sedan   2000  
1         sedan  27150  
2   convertible  54990  
3       4dr_suv  34450  
4        pickup  32340

In [119]:
df.sort_values(by='msrp')

make     model  year  engine_hp  engine_cylinders transmission_type  \
0   nissan    stanza  1991     138.00                 4            manual   
1  hyundai    sonata  2017     202.75                 4         automatic   
4   nissan  frontier  2017     261.00                 6            manual   
3      gmc    acadia  2017     194.00                 4         automatic   
2    lotus     elise  2010     218.00                 4            manual   

  vehicle_style   msrp  
0         sedan   2000  
1         sedan  27150  
4        pickup  32340  
3       4dr_suv  34450  
2   convertible  54990

In [120]:
df.groupby('transmission_type').msrp.mean()

transmission_type
automatic    30800.000000
manual       29776.666667
Name: msrp, dtype: float64

In [121]:
df.groupby('transmission_type').msrp.agg(['mean', 'count'])

mean  count
transmission_type                     
automatic          30800.000000      2
manual             29776.666667      3

In [122]:
df_group = df.groupby('transmission_type').msrp.agg(['mean', 'count'])
df_group

mean  count
transmission_type                     
automatic          30800.000000      2
manual             29776.666667      3

In [123]:
df.msrp


0     2000
1    27150
2    54990
3    34450
4    32340
Name: msrp, dtype: int64

In [125]:
df.msrp


0     2000
1    27150
2    54990
3    34450
4    32340
Name: msrp, dtype: int64

In [126]:
df.msrp.values

array([ 2000, 27150, 54990, 34450, 32340])

In [129]:
np.log1p(df.msrp)

0     7.601402
1    10.209169
2    10.914925
3    10.447293
4    10.384091
Name: msrp, dtype: float64

In [130]:
np.log1p(df.msrp.values)

array([ 7.60140233, 10.20916916, 10.91492481, 10.4472933 , 10.38409105])

In [131]:
df

make     model  year  engine_hp  engine_cylinders transmission_type  \
0   nissan    stanza  1991     138.00                 4            manual   
1  hyundai    sonata  2017     202.75                 4         automatic   
2    lotus     elise  2010     218.00                 4            manual   
3      gmc    acadia  2017     194.00                 4         automatic   
4   nissan  frontier  2017     261.00                 6            manual   

  vehicle_style   msrp  
0         sedan   2000  
1         sedan  27150  
2   convertible  54990  
3       4dr_suv  34450  
4        pickup  32340

In [145]:
df.to_dict(orient='records')

[{'make': 'nissan',
  'model': 'stanza',
  'year': 1991,
  'engine_hp': 138.0,
  'engine_cylinders': 4,
  'transmission_type': 'manual',
  'vehicle_style': 'sedan',
  'msrp': 2000},
 {'make': 'hyundai',
  'model': 'sonata',
  'year': 2017,
  'engine_hp': 202.75,
  'engine_cylinders': 4,
  'transmission_type': 'automatic',
  'vehicle_style': 'sedan',
  'msrp': 27150},
 {'make': 'lotus',
  'model': 'elise',
  'year': 2010,
  'engine_hp': 218.0,
  'engine_cylinders': 4,
  'transmission_type': 'manual',
  'vehicle_style': 'convertible',
  'msrp': 54990},
 {'make': 'gmc',
  'model': 'acadia',
  'year': 2017,
  'engine_hp': 194.0,
  'engine_cylinders': 4,
  'transmission_type': 'automatic',
  'vehicle_style': '4dr_suv',
  'msrp': 34450},
 {'make': 'nissan',
  'model': 'frontier',
  'year': 2017,
  'engine_hp': 261.0,
  'engine_cylinders': 6,
  'transmission_type': 'manual',
  'vehicle_style': 'pickup',
  'msrp': 32340}]