## Machine Learning Zoomcap Intro


In [3]:
import pandas as pd
import numpy as np
import os

In [2]:
pd.__version__

'2.3.1'

In [4]:
os.system("wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv")

--2025-09-29 16:04:39--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 874188 (854K) [text/plain]
Saving to: ‘car_fuel_efficiency.csv’

     0K .......... .......... .......... .......... ..........  5% 61.7M 0s
    50K .......... .......... .......... .......... .......... 11% 66.3M 0s
   100K .......... .......... .......... .......... .......... 17%  369M 0s
   150K .......... .......... .......... .......... .......... 23%  533M 0s
   200K .......... .......... .......... .......... .......... 29%  104M 0s
   250K .......... .......... .......... .......... .......... 35%  108M 0s
   300K .......... .......... .......... .......... .......... 40%  375M 0s
   350K .

0

In [5]:
df = pd.read_csv("car_fuel_efficiency.csv")


In [6]:
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [7]:
df.describe()

engine_displacement  num_cylinders   horsepower  vehicle_weight  \
count          9704.000000    9222.000000  8996.000000     9704.000000   
mean            199.708368       3.962481   149.657292     3001.280993   
std              49.455319       1.999323    29.879555      497.894860   
min              10.000000       0.000000    37.000000      952.681761   
25%             170.000000       3.000000   130.000000     2666.248985   
50%             200.000000       4.000000   149.000000     2993.226296   
75%             230.000000       5.000000   170.000000     3334.957039   
max             380.000000      13.000000   271.000000     4739.077089   

       acceleration   model_year    num_doors  fuel_efficiency_mpg  
count   8774.000000  9704.000000  9202.000000          9704.000000  
mean      15.021928  2011.484027    -0.006412            14.985243  
std        2.510339     6.659808     1.048162             2.556468  
min        6.000000  2000.000000    -4.000000             6.200971  
25%       13.300000  2006.000000    -1.000000            13.267459  
50%       15.000000  2012.000000     0.000000            15.006037  
75%       16.700000  2017.000000     1.000000            16.707965  
max       24.300000  2023.000000     4.000000            25.967222

In [10]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9704 entries, 0 to 9703
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   engine_displacement  9704 non-null   int64  
 1   num_cylinders        9222 non-null   float64
 2   horsepower           8996 non-null   float64
 3   vehicle_weight       9704 non-null   float64
 4   acceleration         8774 non-null   float64
 5   model_year           9704 non-null   int64  
 6   origin               9704 non-null   object 
 7   fuel_type            9704 non-null   object 
 8   drivetrain           9704 non-null   object 
 9   num_doors            9202 non-null   float64
 10  fuel_efficiency_mpg  9704 non-null   float64
dtypes: float64(6), int64(2), object(3)
memory usage: 834.1+ KB


In [11]:
df.nunique()

engine_displacement      36
num_cylinders            14
horsepower              192
vehicle_weight         9704
acceleration            162
model_year               24
origin                    3
fuel_type                 2
drivetrain                2
num_doors                 9
fuel_efficiency_mpg    9704
dtype: int64

In [12]:
df.fuel_type.nunique()

2

In [15]:
df.isnull()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                   False          False       False           False   
1                   False          False       False           False   
2                   False           True       False           False   
3                   False          False        True           False   
4                   False          False       False           False   
...                   ...            ...         ...             ...   
9699                False          False       False           False   
9700                False           True       False           False   
9701                False          False       False           False   
9702                False          False       False           False   
9703                False          False       False           False   

      acceleration  model_year  origin  fuel_type  drivetrain  num_doors  \
0            False       False   False      False       False      False   
1            False       False   False      False       False      False   
2            False       False   False      False       False      False   
3            False       False   False      False       False      False   
4            False       False   False      False       False      False   
...            ...         ...     ...        ...         ...        ...   
9699         False       False   False      False       False       True   
9700         False       False   False      False       False      False   
9701         False       False   False      False       False      False   
9702         False       False   False      False       False      False   
9703         False       False   False      False       False      False   

      fuel_efficiency_mpg  
0                   False  
1                   False  
2                   False  
3                   False  
4                   False  
...                   ...  
9699                False  
9700                False  
9701                False  
9702                False  
9703                False  

[9704 rows x 11 columns]

In [16]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [17]:
df['fuel_efficiency_mpg'].max()

np.float64(25.96722204888372)

In [28]:
df[df['origin'] == 'Asia']

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                     250            1.0       174.0     2714.219310   
12                    320            5.0       145.0     2783.868974   
14                    200            6.0       160.0     3582.687368   
20                    150            3.0       197.0     2231.808142   
21                    160            4.0       133.0     2659.431451   
...                   ...            ...         ...             ...   
9688                  260            4.0         NaN     3948.404625   
9692                  180            3.0       188.0     3680.341381   
9693                  280            2.0       148.0     2545.070139   
9698                  180            1.0       131.0     3107.427820   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8             10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12            15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14            14.9        2007   Asia    Diesel    All-wheel drive        0.0   
20            18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
21             NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   
...            ...         ...    ...       ...                ...        ...   
9688          15.5        2018   Asia    Diesel    All-wheel drive       -1.0   
9692          18.0        2016   Asia  Gasoline  Front-wheel drive        1.0   
9693          15.6        2012   Asia    Diesel    All-wheel drive        0.0   
9698          13.2        2005   Asia  Gasoline  Front-wheel drive       -2.0   
9703          14.7        2005   Asia    Diesel    All-wheel drive       -1.0   

      fuel_efficiency_mpg  
8               16.823554  
12              16.175820  
14              11.871091  
20              18.889083  
21              16.077730  
...                   ...  
9688            11.054830  
9692            11.711653  
9693            17.202782  
9698            13.933716  
9703            14.884467  

[3247 rows x 11 columns]

In [25]:
df[df['origin'] == 'Asia'].fuel_efficiency_mpg.max()

np.float64(23.759122836520497)

In [29]:
df.horsepower.median()

np.float64(149.0)

In [47]:
mode = df.horsepower.mode()
mode[0]

np.float64(152.0)

In [45]:
df.horsepower.isnull().sum()

np.int64(708)

In [48]:
df_f = df.horsepower.fillna(mode[0])

In [51]:
df_f.isnull().sum()

np.int64(0)

In [52]:
df_f.median()

np.float64(152.0)

In [54]:
df.head(2)

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217

In [58]:
asia_cars = df[df['origin'] == 'Asia']
asia_cars.head(2)

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                   250            1.0       174.0     2714.219310   
12                  320            5.0       145.0     2783.868974   

    acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8           10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12          15.1        2010   Asia    Diesel    All-wheel drive        1.0   

    fuel_efficiency_mpg  
8             16.823554  
12            16.175820

In [69]:
asia_cars[['vehicle_weight', 'model_year']].head(7)

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [70]:
X = asia_cars[['vehicle_weight', 'model_year']].head(7).values

In [71]:
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [72]:
# X_transpose multiply by X
XTX = (X.T).dot(X)
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [73]:
# Inverse of XTX
XTX_inverse = np.linalg.inv(XTX)
XTX_inverse

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [74]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [75]:
# Multiply inverse of XTX with X_transpose
a = XTX_inverse.dot(X.T)
w = a.dot(y)
w

array([0.01386421, 0.5049067 ])

In [77]:
w.sum()

np.float64(0.5187709081074016)